import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'ROS 2 Robotic Nervous System',
      items: [
        'ros2-fundamentals',
        'python-agents-rclpy',
        'humanoid-modeling-urdf'
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twins',
      items: [
        'module-2-digital-twins/index',
        {
          type: 'category',
          label: 'Chapter 1: Physics Simulation with Gazebo',
          items: [
            'module-2-digital-twins/chapter-1-gazebo-sim/index',
            'module-2-digital-twins/chapter-1-gazebo-sim/physics-basics',
            'module-2-digital-twins/chapter-1-gazebo-sim/environment-setup',
            'module-2-digital-twins/chapter-1-gazebo-sim/sensor-integration',
            'module-2-digital-twins/chapter-1-gazebo-sim/exercises'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Digital Twin and HRI in Unity',
          items: [
            'module-2-digital-twins/chapter-2-unity-hri/index',
            'module-2-digital-twins/chapter-2-unity-hri/unity-setup',
            'module-2-digital-twins/chapter-2-unity-hri/digital-twin-creation',
            'module-2-digital-twins/chapter-2-unity-hri/hri-concepts',
            'module-2-digital-twins/chapter-2-unity-hri/exercises'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Sensor Simulation and Validation',
          items: [
            'module-2-digital-twins/chapter-3-sensor-validation/index',
            'module-2-digital-twins/chapter-3-sensor-validation/sensor-types',
            'module-2-digital-twins/chapter-3-sensor-validation/validation-methods',
            'module-2-digital-twins/chapter-3-sensor-validation/comparison-tools',
            'module-2-digital-twins/chapter-3-sensor-validation/exercises'
          ],
        },
      ],
    },
  ],
};

export default sidebars;
